# Generated by Django 5.1.4 on 2024-12-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moke', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_mcq',
            field=models.BooleanField(default=True),
        ),
    ]
