# Generated by Django 5.1.4 on 2024-12-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moke', '0002_question_is_mcq'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
